// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"rubbish-cart/rpc/user/internal/logic"
	"rubbish-cart/rpc/user/internal/svc"
	"rubbish-cart/rpc/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetOpenId(ctx context.Context, in *user.GetOpenIdReq) (*user.GetOpenIdResp, error) {
	l := logic.NewGetOpenIdLogic(ctx, s.svcCtx)
	return l.GetOpenId(in)
}

func (s *UserServer) GetPurview(ctx context.Context, in *user.GetPurviewReq) (*user.GetPurviewResp, error) {
	l := logic.NewGetPurviewLogic(ctx, s.svcCtx)
	return l.GetPurview(in)
}

func (s *UserServer) GetRegister(ctx context.Context, in *user.GetRegisterReq) (*user.GetRegisterResp, error) {
	l := logic.NewGetRegisterLogic(ctx, s.svcCtx)
	return l.GetRegister(in)
}

func (s *UserServer) GetUserList(ctx context.Context, in *user.Empty) (*user.GetUserListResp, error) {
	l := logic.NewGetUserListLogic(ctx, s.svcCtx)
	return l.GetUserList(in)
}

func (s *UserServer) UpdateUserInfo(ctx context.Context, in *user.UpdateUserInfoReq) (*user.UpdateUserInfoResp, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}
