// Code generated by goctl. DO NOT EDIT.
package types

type CartRegisterReq struct {
	CartName string `form:"cartName"`
}

type CartRegisterResp struct {
	CartId int `json:"cartId"`
	Resp
}

type CartUpdateReq struct {
	CartId int    `form:"cartId"`
	State  string `form:"state"`
}

type CartUpdateResp struct {
	Resp
}

type AlarmReq struct {
	CartId int    `form:"cartId"`
	Msg    string `form:"msg"`
}

type AlarmResp struct {
	Resp
}

type CartInfo struct {
	CartId   int    `json:"cartId"`
	CartName string `json:"cartName"`
	State    string `json:"state"`
}

type GetInfoResp struct {
	CartInfoList []CartInfo `json:"cartList"`
	Resp
}

type GetOpenIdReq struct {
	Code string `form:"code"`
}

type GetOpenIdResp struct {
	OpenId string `json:"openId"`
	Resp
}

type GetPurviewReq struct {
	OpenId string `form:"openId"`
}

type GetPurviewResp struct {
	Purview int `json:"purview"`
	Resp
}

type GetRegisterReq struct {
	OpenId string `form:"openId"`
	Name   string `form:"name"`
}

type GetRegisterResp struct {
	Purview int `json:"purview"`
	Resp
}

type UserInfo struct {
	OpenId  string `json:"openId"`
	Name    string `json:"name"`
	Purview int    `json:"purview"`
}

type GetUserListResp struct {
	UserList []UserInfo `json:"userList"`
	Resp
}

type UpdateUserInfoReq struct {
	OpenId  string `form:"openId"`
	Name    string `form:"name"`
	Purview int    `form:"purview"`
}

type UpdateUserInfoResp struct {
	Resp
}

type RubbishInfoResp struct {
	CartId int    `json:"cartId"`
	TypeId int    `json:"typeId"`
	Name   string `json:"name"`
	Num    int    `json:"num"`
}

type GetCartRubbishListReq struct {
	CartId int `form:"cartId"`
}

type GetCartRubbishListResp struct {
	RubbishList []RubbishInfoResp `json:"rubbishList"`
	Resp
}

type AddRubbishTypeReq struct {
	Name string `form:"name"`
}

type AddRubbishTypeResp struct {
	Id int `json:"id"`
	Resp
}

type RubbishInfoReq struct {
	CartId int    `form:"cartId"`
	TypeId int    `form:"typeId"`
	Name   string `form:"name"`
	Num    int    `form:"num"`
}

type UpdateCartRubbishReq struct {
	CartId      int              `form:"cartId"`
	RubbishList []RubbishInfoReq `form:"rubbishList"`
}

type UpdateCartRubbishResp struct {
	Resp
}

type Resp struct {
	State int    `json:"state"`
	Msg   string `json:"msg"`
}

type WsReq struct {
}

type WsResp struct {
}
