// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	cart "rubbish-cart/api/internal/handler/cart"
	rubbish "rubbish-cart/api/internal/handler/rubbish"
	user "rubbish-cart/api/internal/handler/user"
	ws "rubbish-cart/api/internal/handler/ws"
	"rubbish-cart/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cart/register",
				Handler: cart.CartRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cart/update",
				Handler: cart.CartUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cart/alarm",
				Handler: cart.AlarmHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/cart/get-info",
				Handler: cart.GetInfoHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/get-openid",
				Handler: user.GetOpenIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/get-purview",
				Handler: user.GetPurviewHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/register",
				Handler: user.GetRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/get-userlist",
				Handler: user.GetUserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/update",
				Handler: user.UpdateUserInfoHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/rubbish/get-rubbish",
				Handler: rubbish.GetCartRubbishListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rubbish/add-type",
				Handler: rubbish.AddRubbishTypeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rubbish/update-rubbish",
				Handler: rubbish.UpdateCartRubbishHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rubbish/type/get-all",
				Handler: rubbish.GetAllTypeHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ws-test",
				Handler: ws.WsTestHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ws",
				Handler: ws.WsHandler(serverCtx),
			},
		},
	)
}
