// Code generated by goctl. DO NOT EDIT!
// Source: rubbish.proto

package server

import (
	"context"

	"rubbish-cart/rpc/rubbish/internal/logic"
	"rubbish-cart/rpc/rubbish/internal/svc"
	"rubbish-cart/rpc/rubbish/rubbish"
)

type RubbishServer struct {
	svcCtx *svc.ServiceContext
}

func NewRubbishServer(svcCtx *svc.ServiceContext) *RubbishServer {
	return &RubbishServer{
		svcCtx: svcCtx,
	}
}

func (s *RubbishServer) GetCartRubbishList(ctx context.Context, in *rubbish.GetCartRubbishListReq) (*rubbish.GetCartRubbishListResp, error) {
	l := logic.NewGetCartRubbishListLogic(ctx, s.svcCtx)
	return l.GetCartRubbishList(in)
}

func (s *RubbishServer) AddRubbishType(ctx context.Context, in *rubbish.AddRubbishTypeReq) (*rubbish.AddRubbishTypeResp, error) {
	l := logic.NewAddRubbishTypeLogic(ctx, s.svcCtx)
	return l.AddRubbishType(in)
}

func (s *RubbishServer) UpdateCartRubbish(ctx context.Context, in *rubbish.UpdateCartRubbishReq) (*rubbish.UpdateCartRubbishResp, error) {
	l := logic.NewUpdateCartRubbishLogic(ctx, s.svcCtx)
	return l.UpdateCartRubbish(in)
}

func (s *RubbishServer) GetTypeAll(ctx context.Context, in *rubbish.Empty) (*rubbish.GetTypeAllResp, error) {
	l := logic.NewGetTypeAllLogic(ctx, s.svcCtx)
	return l.GetTypeAll(in)
}
